// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CSharpSpecflow.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Sample Feature for web applications")]
    [NUnit.Framework.CategoryAttribute("web")]
    public partial class SampleFeatureForWebApplicationsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "web.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Sample Feature for web applications", "\tIn order to demonstrate the value of an open-source automation solution\r\n\tAs a Q" +
                    "A Automation Engineer\r\n\tI want to give an example of how to test using a feature" +
                    " file", ProgrammingLanguage.CSharp, new string[] {
                        "web"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Scenario")]
        [NUnit.Framework.TestCaseAttribute("how wonderful is the Gherkin language?", null)]
        public virtual void TestScenario(string searchString, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Scenario", exampleTags);
#line 7
 this.ScenarioSetup(scenarioInfo);
#line 8
      testRunner.Given("I am a user on Google", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
   testRunner.When(string.Format("I enter text \"{0}\" in the text field \"Search\" by \"id\" with selector \"lst-ib\"", searchString), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
      testRunner.And("I hit Enter by \"id\" with selector \"lst-ib\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
      testRunner.Then("I should be directed to \"Google Search Results\" page by \"id\" with selector \"rcnt\"" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
      testRunner.And("I should see value \"this will fail\" in \"search\" field by \"id\" with selector \"lst-" +
                    "ib\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Tooltip scenario")]
        public virtual void TooltipScenario()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Tooltip scenario", ((string[])(null)));
#line 17
 this.ScenarioSetup(scenarioInfo);
#line 18
  testRunner.Given("I am a user on Mortgage Calculator site", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 19
  testRunner.When("I hover over \"icon next to Mortgage Amount\" by \"cssSelector\" with selector \"#mort" +
                    "ageCalculatorForm > ul.inputFieldList.clearfix.left > li:nth-child(1) > div > a\"" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
  testRunner.Then("I should see \"Mortgage Amount info popup\" with text \"Enter the amount of your new" +
                    " or existing mortgage here.\" by \"cssSelector\" with selector \"#mortageCalculatorF" +
                    "orm > ul.inputFieldList.clearfix.left > li:nth-child(1) > div > a > div\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Calculator scenario")]
        public virtual void CalculatorScenario()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculator scenario", ((string[])(null)));
#line 22
 this.ScenarioSetup(scenarioInfo);
#line 23
  testRunner.Given("I am a user on Mortgage Calculator site", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 24
  testRunner.When("I enter text \"250000\" in the text field \"Mortgage Amount\" by \"id\" with selector \"" +
                    "amount\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 25
  testRunner.And("I enter text \"30\" in the text field \"Amortization Period\" by \"id\" with selector \"" +
                    "amortizationYears\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
  testRunner.And("I enter text \"30\" in the text field \"Interest Terms\" by \"id\" with selector \"inter" +
                    "estTermYears\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
  testRunner.And("I select option \"Fixed\" from dropdown \"Interest Type\" by \"id\" with selector \"inte" +
                    "restType\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
  testRunner.And("I enter text \"4.38\" in the text field \"Interest Rate\" by \"id\" with selector \"rate" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
  testRunner.And("I select option \"10\" from dropdown \"Start Date\" by \"id\" with selector \"startMonth" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
  testRunner.And("I select option \"2017\" from dropdown \"Start Date\" by \"id\" with selector \"startYea" +
                    "r\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
  testRunner.And("I select option \"Monthly\" from dropdown \"Payment period\" by \"id\" with selector \"p" +
                    "aymentMode\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
  testRunner.And("I click \"Calculate Now button\" by \"id\" with selector \"button\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
  testRunner.Then("I should see \"Payment Amount - 1st row\" with text \"$1,248.95\" by \"cssSelector\" wi" +
                    "th selector \"#mortgage > div.calcHolder.flexContainer.mortgage > div.mortageTabl" +
                    "eWrapper > table > tbody > tr.active > td:nth-child(2)\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 34
  testRunner.And("I should see \"Term Interest Cost - 1st row\" with text \"$199,622.19\" by \"cssSelect" +
                    "or\" with selector \"#mortgage > div.calcHolder.flexContainer.mortgage > div.morta" +
                    "geTableWrapper > table > tbody > tr.active > td:nth-child(4)\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
